export interface MockTeacher {
  id: string;
  name: string;
  image: string;
  headline: string;
  bio: string;
  subjects: string[];
  hourlyRate: number;
  currency: string;
  experience: number;
  languages: string[];
  country: string;
  city: string;
  rating: number;
  reviewCount: number;
  totalStudents: number;
  verified: boolean;
  featured: boolean;
  availability: string[];
}

export interface MockReview {
  id: string;
  studentName: string;
  studentImage: string;
  teacherId: string;
  rating: number;
  comment: string;
  date: string;
  subject: string;
}

export interface MockBooking {
  id: string;
  teacherName: string;
  teacherImage: string;
  subject: string;
  date: string;
  time: string;
  duration: number;
  price: number;
  status: 'upcoming' | 'completed' | 'cancelled';
}

export const mockTeachers: MockTeacher[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah',
    headline: 'SAT Expert | 1580 Score | Harvard Graduate',
    bio: 'With over 8 years of experience helping students achieve their dream SAT scores, I have guided more than 500 students to scores above 1500. My approach combines strategic test-taking techniques with deep content mastery. I graduated from Harvard University and have been passionate about education ever since. My students consistently see 200+ point improvements.',
    subjects: ['SAT', 'ACT', 'AP Courses'],
    hourlyRate: 75,
    currency: 'USD',
    experience: 8,
    languages: ['English'],
    country: 'United States',
    city: 'New York',
    rating: 4.9,
    reviewCount: 234,
    totalStudents: 512,
    verified: true,
    featured: true,
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
  {
    id: '2',
    name: 'Aibek Nazarbayev',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aibek',
    headline: 'IELTS 8.5 | Cambridge Certified | 6+ Years',
    bio: 'I am a Cambridge-certified English teacher specializing in IELTS and TOEFL preparation. Having scored 8.5 on IELTS myself, I understand the exam inside and out. I teach in English, Russian, and Kazakh, making my lessons accessible to students across Central Asia. My structured methodology has helped hundreds of students achieve their target band scores.',
    subjects: ['IELTS', 'TOEFL', 'English'],
    hourlyRate: 35,
    currency: 'USD',
    experience: 6,
    languages: ['English', 'Russian', 'Kazakh'],
    country: 'Kazakhstan',
    city: 'Almaty',
    rating: 4.8,
    reviewCount: 189,
    totalStudents: 340,
    verified: true,
    featured: true,
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: '3',
    name: 'Dr. James Chen',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=James',
    headline: 'GRE 340 | PhD Physics | MIT Alumni',
    bio: 'As an MIT PhD graduate in Physics, I bring both academic rigor and practical teaching experience to my GRE and Physics tutoring. I have helped students gain admission to top 20 graduate programs worldwide. My teaching style is patient, methodical, and results-driven.',
    subjects: ['GRE', 'Physics', 'Mathematics'],
    hourlyRate: 90,
    currency: 'USD',
    experience: 12,
    languages: ['English', 'Chinese'],
    country: 'United States',
    city: 'Boston',
    rating: 5.0,
    reviewCount: 156,
    totalStudents: 280,
    verified: true,
    featured: true,
    availability: ['Tue', 'Thu', 'Sat'],
  },
  {
    id: '4',
    name: 'Emma Williams',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Emma',
    headline: 'IELTS Band 9 | British Council Trainer',
    bio: 'Former British Council examiner and trainer with deep insight into the IELTS scoring criteria. I specialize in helping students break through the Band 7+ barrier. My lessons focus on real exam strategies and authentic practice materials.',
    subjects: ['IELTS', 'English', 'A-Levels'],
    hourlyRate: 60,
    currency: 'GBP',
    experience: 10,
    languages: ['English', 'French'],
    country: 'United Kingdom',
    city: 'London',
    rating: 4.9,
    reviewCount: 312,
    totalStudents: 620,
    verified: true,
    featured: true,
    availability: ['Mon', 'Wed', 'Fri'],
  },
  {
    id: '5',
    name: 'Mehmet Yılmaz',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Mehmet',
    headline: 'SAT & TOEFL Specialist | 10 Years Experience',
    bio: 'I have been helping Turkish and international students prepare for SAT and TOEFL for over a decade. My students have been accepted to Ivy League schools, and I take pride in making complex concepts accessible and engaging.',
    subjects: ['SAT', 'TOEFL', 'Mathematics'],
    hourlyRate: 40,
    currency: 'USD',
    experience: 10,
    languages: ['English', 'Turkish'],
    country: 'Turkey',
    city: 'Istanbul',
    rating: 4.7,
    reviewCount: 145,
    totalStudents: 290,
    verified: true,
    featured: false,
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: '6',
    name: 'Minjun Park',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Minjun',
    headline: 'GMAT 780 | McKinsey Consultant | Stanford MBA',
    bio: 'After scoring 780 on the GMAT and graduating from Stanford GSB, I transitioned from management consulting to education. I help ambitious professionals achieve the GMAT scores they need for their dream MBA programs.',
    subjects: ['GMAT', 'GRE', 'Mathematics'],
    hourlyRate: 100,
    currency: 'USD',
    experience: 5,
    languages: ['English', 'Korean'],
    country: 'South Korea',
    city: 'Seoul',
    rating: 4.9,
    reviewCount: 98,
    totalStudents: 180,
    verified: true,
    featured: true,
    availability: ['Mon', 'Wed', 'Fri', 'Sat'],
  },
  {
    id: '7',
    name: 'Anastasia Volkov',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Anastasia',
    headline: 'Chemistry & Biology Expert | PhD Candidate',
    bio: 'Currently pursuing my PhD in Biochemistry at Moscow State University, I am passionate about making science accessible. I teach Chemistry and Biology for IB, A-Levels, and AP exams, as well as university-level courses.',
    subjects: ['Chemistry', 'Biology', 'AP Courses'],
    hourlyRate: 30,
    currency: 'USD',
    experience: 4,
    languages: ['English', 'Russian'],
    country: 'Russia',
    city: 'Moscow',
    rating: 4.6,
    reviewCount: 72,
    totalStudents: 130,
    verified: false,
    featured: false,
    availability: ['Tue', 'Thu', 'Sat', 'Sun'],
  },
  {
    id: '8',
    name: 'David Kim',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=David',
    headline: 'Full-Stack Developer | CS Tutor | Google Ex',
    bio: 'Former Google software engineer turned educator. I teach programming fundamentals, data structures, algorithms, and web development. Whether you are preparing for coding interviews or learning your first programming language, I can help.',
    subjects: ['Programming', 'Mathematics'],
    hourlyRate: 85,
    currency: 'USD',
    experience: 7,
    languages: ['English', 'Korean'],
    country: 'Canada',
    city: 'Toronto',
    rating: 4.8,
    reviewCount: 167,
    totalStudents: 310,
    verified: true,
    featured: false,
    availability: ['Mon', 'Tue', 'Wed', 'Thu'],
  },
  {
    id: '9',
    name: 'Fatima Al-Rashid',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Fatima',
    headline: 'IELTS & Arabic Language Specialist',
    bio: 'Bilingual educator specializing in IELTS preparation and Arabic language instruction. I have helped students from the Middle East achieve Band 7+ scores while also teaching Arabic to international learners.',
    subjects: ['IELTS', 'English'],
    hourlyRate: 45,
    currency: 'USD',
    experience: 8,
    languages: ['English', 'Arabic'],
    country: 'UAE',
    city: 'Dubai',
    rating: 4.7,
    reviewCount: 113,
    totalStudents: 220,
    verified: true,
    featured: false,
    availability: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
  },
  {
    id: '10',
    name: 'Prof. Hans Weber',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Hans',
    headline: 'Mathematics Professor | 20+ Years Teaching',
    bio: 'Retired university professor with over two decades of teaching experience. I specialize in advanced mathematics, calculus, linear algebra, and mathematical olympiad preparation. My approach builds deep understanding from first principles.',
    subjects: ['Mathematics', 'Physics', 'A-Levels'],
    hourlyRate: 55,
    currency: 'EUR',
    experience: 22,
    languages: ['English', 'German'],
    country: 'Germany',
    city: 'Berlin',
    rating: 4.8,
    reviewCount: 201,
    totalStudents: 450,
    verified: true,
    featured: false,
    availability: ['Mon', 'Wed', 'Fri'],
  },
  {
    id: '11',
    name: 'Priya Sharma',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Priya',
    headline: 'MCAT 528 | Medical School Advisor',
    bio: 'Scored a perfect 528 on the MCAT and now dedicated to helping pre-med students achieve exceptional scores. I also provide medical school admissions consulting, including personal statement review and interview prep.',
    subjects: ['MCAT', 'Biology', 'Chemistry'],
    hourlyRate: 95,
    currency: 'USD',
    experience: 6,
    languages: ['English'],
    country: 'India',
    city: 'Mumbai',
    rating: 4.9,
    reviewCount: 87,
    totalStudents: 160,
    verified: true,
    featured: true,
    availability: ['Mon', 'Tue', 'Thu', 'Sat'],
  },
  {
    id: '12',
    name: 'Yuki Tanaka',
    image: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Yuki',
    headline: 'TOEFL 120 | English & Japanese Instructor',
    bio: 'Achieved a perfect TOEFL score and now helping Japanese and international students master English proficiency exams. My unique bilingual teaching method bridges the gap between Japanese and English thinking patterns.',
    subjects: ['TOEFL', 'IELTS', 'English'],
    hourlyRate: 50,
    currency: 'USD',
    experience: 5,
    languages: ['English', 'Chinese', 'Korean'],
    country: 'Japan',
    city: 'Tokyo',
    rating: 4.7,
    reviewCount: 94,
    totalStudents: 175,
    verified: true,
    featured: false,
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
];

export const mockReviews: MockReview[] = [
  {
    id: 'r1',
    studentName: 'Alex Turner',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Alex',
    teacherId: '1',
    rating: 5,
    comment: 'Sarah is an incredible SAT tutor! My score improved from 1320 to 1540 in just 3 months. Her strategies for the reading section are game-changing.',
    date: '2025-12-15',
    subject: 'SAT',
  },
  {
    id: 'r2',
    studentName: 'Daulet Akhmetov',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Daulet',
    teacherId: '2',
    rating: 5,
    comment: 'Aibek helped me go from IELTS 5.5 to 7.5. His teaching in Russian made complex concepts much easier to understand. Highly recommended!',
    date: '2025-11-20',
    subject: 'IELTS',
  },
  {
    id: 'r3',
    studentName: 'Michelle Lee',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Michelle',
    teacherId: '3',
    rating: 5,
    comment: 'Dr. Chen is a phenomenal GRE tutor. His explanations of quant concepts are crystal clear. Got a 335 thanks to him!',
    date: '2025-10-08',
    subject: 'GRE',
  },
  {
    id: 'r4',
    studentName: 'Omar Hassan',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Omar',
    teacherId: '4',
    rating: 5,
    comment: 'Emma\'s insider knowledge as a former examiner is invaluable. She knows exactly what examiners look for. Got Band 8!',
    date: '2025-09-14',
    subject: 'IELTS',
  },
  {
    id: 'r5',
    studentName: 'Elif Demir',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Elif',
    teacherId: '5',
    rating: 4,
    comment: 'Mehmet is very knowledgeable and patient. He explained SAT math strategies in a way I could easily follow. Great teacher!',
    date: '2025-08-22',
    subject: 'SAT',
  },
  {
    id: 'r6',
    studentName: 'Jiwon Kim',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Jiwon',
    teacherId: '6',
    rating: 5,
    comment: 'Minjun\'s GMAT strategies are incredible. He helped me score 760 and get into Wharton. Worth every penny!',
    date: '2025-07-30',
    subject: 'GMAT',
  },
  {
    id: 'r7',
    studentName: 'Anna Petrova',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Anna',
    teacherId: '7',
    rating: 5,
    comment: 'Anastasia makes chemistry so interesting! She uses great analogies and real-world examples. My IB score went from 4 to 7.',
    date: '2025-07-15',
    subject: 'Chemistry',
  },
  {
    id: 'r8',
    studentName: 'Jason Park',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Jason',
    teacherId: '8',
    rating: 5,
    comment: 'David\'s coding lessons transformed my understanding of algorithms. I went from struggling with basics to passing Google interviews.',
    date: '2025-06-20',
    subject: 'Programming',
  },
  {
    id: 'r9',
    studentName: 'Layla Ahmad',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Layla',
    teacherId: '9',
    rating: 5,
    comment: 'Fatima is an amazing IELTS tutor. Her bilingual approach helped me understand nuances I was missing. Got 7.5 overall!',
    date: '2025-06-01',
    subject: 'IELTS',
  },
  {
    id: 'r10',
    studentName: 'Thomas Mueller',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Thomas',
    teacherId: '10',
    rating: 5,
    comment: 'Prof. Weber\'s depth of mathematical knowledge is extraordinary. He helped me win a regional math olympiad. A true master.',
    date: '2025-05-12',
    subject: 'Mathematics',
  },
  {
    id: 'r11',
    studentName: 'Rachel Green',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rachel',
    teacherId: '11',
    rating: 5,
    comment: 'Priya\'s MCAT preparation is unmatched. Her systematic approach to each section gave me the confidence to score 525.',
    date: '2025-04-28',
    subject: 'MCAT',
  },
  {
    id: 'r12',
    studentName: 'Kenji Watanabe',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Kenji',
    teacherId: '12',
    rating: 4,
    comment: 'Yuki\'s bilingual teaching method is unique and effective. She understands the challenges Japanese speakers face with English.',
    date: '2025-04-10',
    subject: 'TOEFL',
  },
  {
    id: 'r13',
    studentName: 'Sofia Martinez',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia',
    teacherId: '1',
    rating: 5,
    comment: 'Best SAT tutor I\'ve ever had. Sarah\'s personalized study plan was exactly what I needed. 1510 final score!',
    date: '2025-03-20',
    subject: 'SAT',
  },
  {
    id: 'r14',
    studentName: 'Arman Bekturov',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Arman',
    teacherId: '2',
    rating: 5,
    comment: 'Aibek aga is the best IELTS teacher in KZ. He explains everything clearly in both Russian and English. Got my target score!',
    date: '2025-03-05',
    subject: 'IELTS',
  },
  {
    id: 'r15',
    studentName: 'Emily Watson',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Emily',
    teacherId: '4',
    rating: 4,
    comment: 'Emma\'s writing feedback is incredibly detailed. She helped me improve my essay score from 6.0 to 7.5. Very professional.',
    date: '2025-02-18',
    subject: 'IELTS',
  },
  {
    id: 'r16',
    studentName: 'Ryan Kim',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ryan',
    teacherId: '8',
    rating: 4,
    comment: 'David is a great programming tutor. His real-world experience from Google adds so much value to the lessons.',
    date: '2025-02-01',
    subject: 'Programming',
  },
  {
    id: 'r17',
    studentName: 'Aygerim Suleimen',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aygerim',
    teacherId: '2',
    rating: 5,
    comment: 'Incredible teacher! Aibek helped me prepare for IELTS in just 2 months. His speaking practice sessions are the best.',
    date: '2025-01-25',
    subject: 'IELTS',
  },
  {
    id: 'r18',
    studentName: 'Daniel Brown',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Daniel',
    teacherId: '3',
    rating: 5,
    comment: 'Dr. Chen\'s physics tutoring is exceptional. He breaks down complex topics into digestible pieces. Highly recommend!',
    date: '2025-01-10',
    subject: 'Physics',
  },
  {
    id: 'r19',
    studentName: 'Chloe Martin',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chloe',
    teacherId: '6',
    rating: 5,
    comment: 'Minjun\'s approach to GMAT quant is brilliant. His shortcuts and strategies saved me so much time on test day.',
    date: '2024-12-20',
    subject: 'GMAT',
  },
  {
    id: 'r20',
    studentName: 'Nurlan Omarov',
    studentImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Nurlan',
    teacherId: '5',
    rating: 5,
    comment: 'Mehmet hoca SAT math section\'ini çok iyi anlatıyor. Highly recommended for Turkish students preparing for US universities.',
    date: '2024-12-05',
    subject: 'SAT',
  },
];

export const mockBookings: MockBooking[] = [
  {
    id: 'b1',
    teacherName: 'Sarah Johnson',
    teacherImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah',
    subject: 'SAT',
    date: '2026-07-15',
    time: '14:00',
    duration: 60,
    price: 75,
    status: 'upcoming',
  },
  {
    id: 'b2',
    teacherName: 'Aibek Nazarbayev',
    teacherImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aibek',
    subject: 'IELTS',
    date: '2026-07-16',
    time: '10:00',
    duration: 90,
    price: 52,
    status: 'upcoming',
  },
  {
    id: 'b3',
    teacherName: 'Dr. James Chen',
    teacherImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=James',
    subject: 'GRE',
    date: '2026-07-10',
    time: '16:00',
    duration: 60,
    price: 90,
    status: 'completed',
  },
  {
    id: 'b4',
    teacherName: 'Emma Williams',
    teacherImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Emma',
    subject: 'IELTS',
    date: '2026-07-08',
    time: '11:00',
    duration: 60,
    price: 60,
    status: 'completed',
  },
  {
    id: 'b5',
    teacherName: 'David Kim',
    teacherImage: 'https://api.dicebear.com/9.x/avataaars/svg?seed=David',
    subject: 'Programming',
    date: '2026-07-05',
    time: '09:00',
    duration: 120,
    price: 170,
    status: 'cancelled',
  },
];
